import QueryProvider from '@/lib/QueryProvider'
import type { Metadata } from 'next'
import './globals.css'
import AntdProvider from '@/lib/AntdProvider'
import '@ant-design/v5-patch-for-react-19'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <AntdProvider>
          <body>{children}</body>
        </AntdProvider>
      </QueryProvider>
    </html>
  )
}
